version: '3.7'  
services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: 'db_laravellynda'
        # MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_PASSWORD: "123"
        # Log in: db, root, 123
    volumes:
        - ./dbfiles:/var/lib/mysql
    command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
  
  app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    image: 'laravellynda'
    ports:
        - 8080:80
    volumes:
        - ./:/var/www/html

  adminer:           # имя контейнера
    image: adminer
    restart: on-failure
    ports:           # порт - локальный:внутри_контейнера
      - 6080:8080
    environment:
      ADMINER_DESIGN: rmsoft_blue # синее оформление
  